server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: contest-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: contest-user
          uri: lb://contest-user
          predicates:
            - Path=/login/**,/register/**,/modify/**,/user/**
        - id: contest-filesys
          uri: lb://contest-filesys
          predicates:
            - Path=/filesys/**
        - id: contest-online
          uri: lb://contest-online
          predicates:
            - Path=/contest/online/**
        - id: contest-enroll
          uri: lb://contest-enroll
          predicates:
            - Path=/contest/enroll/**
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

uri:
  auth:
    skipping:
      - /login
      - /register
      - /modify
      - /filesys/download
      - /user/pic/get