export const QUESTION_TYPE = {
    SINGLE_OPTION_QUESTION: 'SINGLE_OPTION_QUESTION',
    SUPPLEMENT_QUESTION: 'SUPPLEMENT_QUESTION',
    JUDGE_QUESTION: 'JUDGE_QUESTION',
    ANSWER_QUESTION: 'ANSWER_QUESTION',
    PROGRAMMING_QUESTION: 'PROGRAMMING_QUESTION',
    NULL: 'NULL'
}

export const PROGRAM_EXAMPLE_TYPE = {
    INPUT_EXAMPLE: 'INPUT_EXAMPLE',
    OUTPUT_EXAMPLE: 'OUTPUT_EXAMPLE'
}

export const questionTypeMap = {
    ANSWER_QUESTION: '问答题',
    SINGLE_OPTION_QUESTION: '选择题',
    SUPPLEMENT_QUESTION: '填空题',
    JUDGE_QUESTION: '判断题',
    PROGRAMMING_QUESTION: '编程题'
}