export const QUESTION_TYPE = {
    SINGLE_OPTION_QUESTION: 'SINGLE_OPTION_QUESTION',
    SUPPLEMENT_QUESTION: 'SUPPLEMENT_QUESTION',
    JUDGE_QUESTION: 'JUDGE_QUESTION',
    ANSWER_QUESTION: 'ANSWER_QUESTION',
}