export const QUESTION_TYPE = {
    SINGLE_OPTION_QUESTION: 'SINGLE_OPTION_QUESTION',
    SUPPLEMENT_QUESTION: 'SUPPLEMENT_QUESTION',
    JUDGE_QUESTION: 'JUDGE_QUESTION',
    ANSWER_QUESTION: 'ANSWER_QUESTION',
    PROGRAMMING_QUESTION: 'PROGRAMMING_QUESTION',
    NULL: 'NULL'
}

export const PROGRAM_EXAMPLE_TYPE = {
    INPUT_EXAMPLE: 'INPUT_EXAMPLE',
    OUTPUT_EXAMPLE: 'OUTPUT_EXAMPLE'
}